/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreviousTune.java
 *
 * Created on May 12, 2013, 1:15:44 AM
 */

package cloudserver;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import java.util.Vector;
import org.jfugue.Pattern;
import org.jfugue.Player;

public class PreviousTune extends javax.swing.JFrame {

    /** Creates new form PreviousTune */
    public PreviousTune() {
        initComponents();
        listData = new Vector();
        MySqlConnection mysql = new MySqlConnection();
        try
        {
            Connection con = mysql.getMySQLConnection();
            String query = "SELECT input  FROM DATA";
            System.out.println("Query - "+query);
            PreparedStatement stmt = con.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            while(rs.next())
            {
               jComboBox1.addItem(rs.getString(1));
            }
        }
        catch(Exception e)
        {
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jComboBox1.setBackground(new java.awt.Color(202, 122, 36));
        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(100, 110, 290, 30);

        outputList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        outputList.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        outputList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                outputListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(outputList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 160, 290, 290);

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloudserver/z_Buttons_play.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 0, 102)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 470, 120, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloudserver/z_Buttons_back.jpg"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 0, 102)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 470, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cloudserver/z_player.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(850, 650));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        int  i = jComboBox1.getSelectedIndex();
        System.out.println("Item Selected Index: " +i);
        String selectedTuneCombination = null;
        MySqlConnection mysql =  new MySqlConnection();
        try
        {
                Connection con = (Connection) mysql.getMySQLConnection();
                i++;
                String query = "SELECT output FROM DATA where tune_id = "+i+"";
                System.out.println("delect data: "+query);
                PreparedStatement stmt = con.prepareStatement(query);
                ResultSet rs = stmt.executeQuery();
                while(rs.next())
                {
                    selectedTuneCombination = rs.getString(1);
                }
                listData.clear();
                if(selectedTuneCombination != null)
                {
                    StringTokenizer token = new StringTokenizer(selectedTuneCombination , ":");
                    while(token.hasMoreTokens())
                    {
                        listData.add(token.nextToken());
                    }
                    outputList.setListData(listData);
                }
               
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void outputListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_outputListValueChanged

}//GEN-LAST:event_outputListValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sargam = (String)listData.get(outputList.getSelectedIndex());
        Pattern pattern=new Pattern(sargam);
        Player player=new Player();
        player.play(pattern);
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminArea area = new AdminArea();
        area.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviousTune().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList outputList;
    // End of variables declaration//GEN-END:variables
    private Vector listData;
}
